// manifest import and workbox imports will be autogenerated by webpack
<<<<<<< HEAD
//workbox.precaching.precacheAndRoute(self.__precacheManifest || []);
=======
/*workbox.precaching.precacheAndRoute(self.__precacheManifest || []);*/
>>>>>>> 5032817ae10d145f9ebe3516f75bacf93d5095e4
